import test from 'node:test';
import assert from 'node:assert/strict';
import { parseNote, renderMarkdown, renderInline, resolvePath, validateNotePath, createResolver, buildKnowledgeIndex, toggleTask, safeExternalUrl, searchNotes } from '../core.mjs';
const notes = (...entries) => new Map(entries.map(([path, content]) => [path, parseNote(path, content)]));

test('frontmatter title, list tags, aliases and Unicode headings', () => {
  const note = parseNote('fallback.md', '---\ntitle: "Ý tưởng"\ntags:\n  - research\n  - systems\naliases: [Idea, Concept]\n---\n# A heading\n\n#inline-tag');
  assert.equal(note.title, 'Ý tưởng'); assert.deepEqual(note.tags, ['research', 'systems', 'inline-tag']); assert.deepEqual(note.aliases, ['Idea', 'Concept']);
});
test('unclosed frontmatter stays in the body', () => { const note = parseNote('file.md', '---\ntitle: Not metadata\n# Visible'); assert.equal(note.title, 'Visible'); assert.equal(note.frontmatter, ''); });
test('fallback title and duplicate heading IDs', () => { const note = parseNote('some/note.markdown', '## Section\n## Section'); assert.equal(note.title, 'note'); assert.deepEqual(note.headings.map((h) => h.id), ['section', 'section-1']); });
test('wikilinks and Markdown links are indexed, code and images are not', () => {
  const note = parseNote('a.md', '[[B#Heading|alias]] and [C](C.md) and **[[D]]**.\n\n`[[Inline]]`\n\n```md\n[[Fenced]]\n```\n\n![[image.png]]\n\n[external](https://example.com)');
  assert.deepEqual(note.links.map((l) => l.target), ['B#Heading', 'C.md', 'D']);
});
test('fence delimiters respect length and kind', () => { const note = parseNote('a.md', '````\n```\n[[Not a link]]\n````\n[[Real]]'); assert.deepEqual(note.links.map((l) => l.target), ['Real']); });
test('escaped wikilinks and code remain literal', () => { assert.equal(parseNote('a.md', '\\[[Not a link]] and ``[[Code]]``').links.length, 0); });
test('sibling-relative and root-relative note paths', () => { const map = notes(['A/Start.md', '# Start'], ['A/B.md', '# B'], ['B.md', '# Root B']); const resolve = createResolver(map); assert.equal(resolve('B', 'A/Start.md').note.path, 'A/B.md'); assert.equal(resolve('/B.md', 'A/Start.md').note.path, 'B.md'); assert.equal(resolve('../B.md#Section', 'A/Start.md').heading, 'Section'); });
test('aliases, names with spaces and hyphenated filenames', () => { const map = notes(['getting-started.md', '---\naliases: [Guide]\n---\n# Getting Started']); const resolve = createResolver(map); assert.equal(resolve('Getting Started', 'Other.md').note.path, 'getting-started.md'); assert.equal(resolve('Guide', 'Other.md').note.path, 'getting-started.md'); assert.equal(resolve('getting%20started', 'Other.md').note.path, 'getting-started.md'); });
test('ambiguous basenames are never resolved arbitrarily', () => { const map = notes(['A/Idea.md', '# Idea'], ['B/Idea.md', '# Idea']); const result = createResolver(map)('Idea', 'Home.md'); assert.equal(result.note, null); assert.equal(result.matches.length, 2); });
test('case collisions are ambiguous even for full paths', () => { const map = notes(['A.md', '# One'], ['a.md', '# Two']); assert.equal(createResolver(map)('a.md', '').matches.length, 2); });
test('same-note anchors resolve without generating self-edges', () => { const map = notes(['A.md', '# A\n\n[section](#A)\n[[A]]']); assert.equal(createResolver(map)('#A', 'A.md').note.path, 'A.md'); assert.equal(buildKnowledgeIndex(map).edges.length, 0); });
test('deduplicated backlinks and unresolved links', () => { const map = notes(['A.md', '# A\n[[B]] [[B#Heading]] [[Missing]]'], ['B.md', '# B']); const index = buildKnowledgeIndex(map); assert.deepEqual(index.edges, [{ source: 'A.md', target: 'B.md' }]); assert.deepEqual(index.backlinks.get('B.md'), ['A.md']); assert.equal(index.unresolved.get('A.md')[0].target, 'Missing'); });
test('vault paths reject escape, hidden paths, bad encoding and schemes', () => { for (const path of ['../../private', 'https://example.com', '//example.com/a', '%ZZ', '.git/config', 'A/../.env', 'C:\\secrets', '%2e%2e/%2e%2e/outside']) assert.equal(resolvePath(path, 'Research/a.md'), null, path); assert.equal(resolvePath('../assets/image.png', 'Research/a.md'), 'assets/image.png'); });
test('new note paths are portable and cannot escape the root', () => { for (const path of ['../secret', '.git/x', 'a//b', '/absolute', 'A/CON.md', 'bad?.md', 'bad\\name.md', 'a/.. /x']) assert.throws(() => validateNotePath(path), Error, path); assert.equal(validateNotePath('Research/Ý tưởng'), 'Research/Ý tưởng.md'); assert.equal(validateNotePath('A.MARKDOWN'), 'A.MARKDOWN'); });
test('task toggling preserves CRLF, BOM, metadata, and other bytes', () => { const source = '\uFEFF---\r\ntags: [work]\r\n---\r\n# Plan\r\n- [ ] first\r\n- [x] second\r\n'; const note = parseNote('a.md', source); assert.equal(note.tasks[0].line, 4); assert.equal(toggleTask(source, 4, true), source.replace('- [ ] first', '- [x] first')); assert.equal(toggleTask(source, 3, true), source); });
test('raw HTML and attribute injection are escaped', () => { const html = renderMarkdown(parseNote('a.md', '<img src=x onerror="window.pwned=1">\n\n[[A" onclick="alert(1)|click]]')); assert.ok(!html.includes('<img')); assert.ok(html.includes('&lt;img')); assert.ok(!html.includes('data-link="A" onclick')); });
test('active URL schemes and protocol-relative links cannot render anchors', () => { for (const url of ['javascript:alert(1)', 'data:text/html,hello', 'vbscript:foo', '//evil.test', 'java\nscript:foo']) assert.ok(!renderInline(`[x](${url})`).includes('<a '), url); });
test('safe external links have noopener and noreferrer', () => { assert.equal(safeExternalUrl('https://example.com'), 'https://example.com/'); assert.equal(safeExternalUrl('mailto:a@example.com'), 'mailto:a@example.com'); assert.equal(safeExternalUrl('https://example.com\n'), null); assert.match(renderInline('[site](https://example.com)'), /rel="noopener noreferrer"/); });
test('images are inert placeholders until explicitly resolved inside the vault', () => { const html = renderInline('![remote](https://evil.test/tracker.png)'); assert.match(html, /data-asset=/); assert.ok(!html.includes('<img')); assert.ok(!html.includes(' src=')); });
test('tables, task lists, inline emphasis and fenced code render', () => { const html = renderMarkdown(parseNote('a.md', '| A | B |\n| --- | --- |\n| **one** | two |\n\n- [x] Done\n\n```js\n<script>\n```')); assert.match(html, /<table>/); assert.match(html, /<strong>one<\/strong>/); assert.match(html, /type="checkbox".* checked/); assert.match(html, /&lt;script&gt;/); });
test('full-text, tag and title-ranked search', () => { const map = notes(['A.md', '# Other\n\nneedle #systems'], ['B.md', '# Needle\n\n#systems'], ['C.md', '# C']); assert.deepEqual(searchNotes(map, 'needle').map((n) => n.path), ['B.md', 'A.md']); assert.equal(searchNotes(map, '#systems').length, 2); assert.equal(searchNotes(map, 'needle', 'systems').length, 2); assert.equal(searchNotes(map, 'missing').length, 0); });
test('recent search uses modification time and stable path tie breaks', () => { const map = notes(['B.md', '# B'], ['A.md', '# A']); map.get('B.md').modified = 10; assert.equal(searchNotes(map, '', '', true)[0].path, 'B.md'); });
